Token request example
romadanskiy/MicroDotNet pull request #2
Opened 2022-04-12 10:25 UTC by R0manych

https://yt.hightech.group/issue/HT-28
Authorization token request example

2022-04-12 10:38 UTC, R0manych commented on src/services/auth-demo/package.json
> +  "proxy":"http://localhost:5000",
мой комментарий

2022-04-12 10:40 UTC, max-arshinov requested changes

2022-04-12 10:40 UTC, max-arshinov commented on src/services/auth/Auth.Web/Controllers/ExampleController.cs
> +        [Authorize(AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)]
А тут можно же сделать AuthorizeViaBearer: Authorize(AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme), чтобы покороче было?

2022-04-12 10:40 UTC, max-arshinov commented on src/services/auth/Auth.Web/StartupExtensions.cs
> +            }).AddValidation(options =>
Напомни, это настройки OpenIddict, которые учат работать с этим атрибутом [Authorize(AuthenticationSchemes = OpenIddictValidationAspNetCoreDefaults.AuthenticationScheme)] ?

2022-04-12 10:53 UTC, R0manych commented on src/services/auth/Auth.Web/StartupExtensions.cs
> +            }).AddValidation(options =>
Да, для этого

2022-04-13 10:18 UTC, max-arshinov approved these changes

2022-04-13 10:19 UTC, merged